### ISSUE TITLE
Rewrite in Rust

### ISSUE THREAD

**Issue by Seriklol** [Nymnion/nymnge#1]
Why Rust?

Performance:
Rust is blazingly fast and memory-efficient: with no runtime or garbage collector, it can power performance-critical services, run on embedded devices, and easily integrate with other languages.

Reliability:
Rust’s rich type system and ownership model guarantee memory-safety and thread-safety — enabling you to eliminate many classes of bugs at compile-time.

Productivity:
Rust has great documentation, a friendly compiler with useful error messages, and top-notch tooling — an integrated package manager and build tool, smart multi-editor support with auto-completion and type inspections, an auto-formatter, and more.

**Comment by gempir** [comment]
![image](https://github.com/Nymnion/nymnge/assets/9765622/cb90d55c-4c48-4da5-b7cd-20288748c40e)
